### ISSUE TITLE
Configuring mobs/entities with inventory space to preserve food

### ISSUE THREAD

**Issue by WrongWeekend** [Stormwind99/FoodFunk#18]
It would be helpful if entities with inventory space could be configured to stop food spoilage while the food item is stored in their inventory. Some examples in vanilla would be mules, donkeys, and minecarts with chests. A number of mods also add mounts or vehicles with inventory space. In particular, I am interested in potentially using Immersive Railroading refrigerator cars to transport food while preserving it.

**Comment by Stormwind99** [comment]
I like it!  I put it on the todo list.

**Comment by Stormwind99** [comment]
Done in https://github.com/Stormwind99/FoodFunk/commit/62b97e64043c111d20c469f3aa8ec5664ff84eca

**Comment by Stormwind99** [comment]
Check out Food Funk 3.0.0
