### ISSUE TITLE
Crash on initialization with Food Funk

### ISSUE THREAD

**Issue by MessyConfessor** [Stormwind99/FoodFunk#25]
I got a crash log that was labeled as being caused by both Food Funk and Additional Banners: https://pastebin.com/arUb5NXZ

So I disabled Additional Banners, and got a similar log labeled for Food Funk and Quark: https://pastebin.com/QNQvEKc0

Any idea what's happening here?

**Comment by MessyConfessor** [comment]
Just tried that, still getting the same crash. Although now it's flagging Extra Utilities 2 instead of the others, so...I dunno.

**Comment by Stormwind99** [comment]
Try version 4.0.4 which I just pushed.   If it isn't on Curseforge yet you can download it from Github releases: https://github.com/Stormwind99/FoodFunk/releases/tag/4.0.4

**Comment by Stormwind99** [comment]
Actually, try version 4.0.5 - I added another defense there too.

https://github.com/Stormwind99/FoodFunk/releases/tag/4.0.5
