### ISSUE TITLE
startup crash with applecore

### ISSUE THREAD

**Issue by codydbgt** [Stormwind99/FoodFunk#37]
this simply just crashes with apple core

**Comment by Stormwind99** [comment]
I can't duplicate the issue - I just ran AppleCore, FoodFunk, and WumpleUtil mods together without a startup crash using forge-14.23.4.2760.

Please upload all mods and Forge and try again - and if it crashes, please attach a crash report and info requested in the bug reporting template.

**Comment by Stormwind99** [comment]
Food Funk 4.9.5 may fix this crash by disabling replaceSpecialThings when applecore and betterwithmods are loaded.

https://github.com/Stormwind99/FoodFunk/commit/5934a0bfea700039c92bedbbe042c60788b37640
