### ISSUE TITLE
Crashes with botania

### ISSUE THREAD

**Issue by Novotisy** [Stormwind99/FoodFunk#39]
[crash-2018-09-07_14.54.52-client.txt](https://github.com/Stormwind99/FoodFunk/files/2362188/crash-2018-09-07_14.54.52-client.txt)

**Comment by Stormwind99** [comment]
I was not able to duplicate this crash running latest forge 2760 build with Food Funk, Wumple Util, Botania, and Baubles mods.

I'd guess some other mod installed is causing the incompatibility.  To find the mod responsible, I suggest disabling all mods but the above, then enabling the mods one at a time (plus the dependencies on the mod enables) until duplicating the crash.

**Comment by Stormwind99** [comment]
Food Funk 4.9.6 may have a workaround for this crash - can you try it out?
