### ISSUE TITLE
Conflicts with Applecore

### ISSUE THREAD

**Issue by fin600** [Stormwind99/FoodFunk#42]
Latest foodfunk does something that conflicts with applecore, crashing the game.

**Comment by Stormwind99** [comment]
I have not been able to duplicate this issue.  Can you attach the latest log, foodfunk log, and wumpleutil log from the crash?

**Comment by Stormwind99** [comment]
#37 duplicates this

**Comment by Stormwind99** [comment]
Food Funk 4.9.5 may fix this crash by disabling replaceSpecialThings when applecore and betterwithmods are loaded.

https://github.com/Stormwind99/FoodFunk/commit/5934a0bfea700039c92bedbbe042c60788b37640
