### ISSUE TITLE
Config keeps "resetting"

### ISSUE THREAD

**Issue by Ash70** [Stormwind99/FoodFunk#44]
**Describe the bug**
When I remove some entries from the config file, they reappear once the game starts.

**Expected behavior**
I'd expect the config to respect my changes, even if these are removals.

**Comment by Stormwind99** [comment]
Instead of removing items from the config file, put in an "no decay" entry. Example:
I:"foodfunk:rotten_food"=-1

This is due to the default values system that adds any missing default values to the config.
