### ISSUE TITLE
Strange crash between this mod and crystals

### ISSUE THREAD

**Issue by Sunconure11** [Stormwind99/FoodFunk#51]
https://pastebin.com/ZZ6VsmpS

https://minecraft.curseforge.com/projects/crystals?gameCategorySlug=mc-mods&projectID=291524

These two mods should not be touching each other...

**Comment by Sunconure11** [comment]
@therealfarfetchd @Stormwind99

**Comment by therealfarfetchd** [comment]
Should be fixed by https://github.com/amadornes/ModJam5/commit/752b99f32fd5f6b34286760d8dda093ca78efa88

**Comment by Sunconure11** [comment]
That seems to have worked, I'm just fighting with curse at the moment, since it's not taking the new build in my pack.

**Comment by Stormwind99** [comment]
Closing since reported to have worked.

**Comment by Sunconure11** [comment]
Oh, seeing this mod, can you add an option for certain items to be ignored, such as rustic and TaN drinks? I know some things like this had issues with this mod, thus preventing TaN’s thirst from working right.
