### ISSUE TITLE
Crash with Industrialcraft 2 

### ISSUE THREAD

**Issue by Pival81** [Stormwind99/FoodFunk#60]
**Describe the bug**
The game crashes at launch

**To Reproduce**
Launch the game

**Expected behavior**

**Logs**
[crash log](https://paste.dimdev.org/jagaberevu.mccrash)

The log is critical - it contains the versions of the mod, Forge, and Minecraft being used in addition to other needed information.

**Config files**
Attach the configuration files related to this issue, usually foodfunk.cfg and wumpleutil.cfg at minimum.

**Screenshots**

**Additional context**

**Comment by sergeycherepanov** [comment]
The related issue from IC2 forum https://bt.industrial-craft.net/view.php?id=2534

The issue happens only if IC2 Advanced Machines mod installed. 

Is there is a way to resolve it?

**Comment by Stormwind99** [comment]
Possibly dupe of #56

**Comment by Stormwind99** [comment]
Food Funk 4.9.6 may have a workaround for this crash - can you try it out?

**Comment by Stormwind99** [comment]
After mod compat workarounds made in Food Funk 4.9.6 and WumpleUtil 2.12.9, I can no longer reproduce this crash with IC2 (industrialcraft-2-2.8.170-ex112.jar) and IC2 Advanced Machines (Advanced Machines-61.0.1.jar).
