### ISSUE TITLE
Conflict with some mods on server and client

### ISSUE THREAD

**Issue by cofinman** [Stormwind99/FoodFunk#9]
Hi, there is some info about problem with some mods. Client and server crash on start when FoodFunk installed with each of:
-Erebus
-Better with Mods
-Aquaculture
-Biomes o planty
I know nothing about minecraft modding, but it looks like similar problem with each of them. Dat would be nice if you fix those problems. Because "BoP" is very popular mod and i think some of users can have similar problems in future. Thx
Forge version: 1.12.2 - 14.23.4.2705

[crash-2018-05-17_15.04.19-client.txt](https://github.com/Stormwind99/FoodFunk/files/2152058/crash-2018-05-17_15.04.19-client.txt)
[crash-2018-06-30_20.27.32-server.txt](https://github.com/Stormwind99/FoodFunk/files/2152060/crash-2018-06-30_20.27.32-server.txt)
[crash-2018-06-30_20.28.01-server.txt](https://github.com/Stormwind99/FoodFunk/files/2152061/crash-2018-06-30_20.28.01-server.txt)
[crash-2018-06-30_20.26.09-server.txt](https://github.com/Stormwind99/FoodFunk/files/2152062/crash-2018-06-30_20.26.09-server.txt)
[crash-2018-06-30_20.27.10-server.txt](https://github.com/Stormwind99/FoodFunk/files/2152064/crash-2018-06-30_20.27.10-server.txt)

**Comment by Stormwind99** [comment]
Forge devs report that those other mods are doing bad things - by not using events for registration, they are doing things too early.  I'm trying to work around it.

**Comment by Stormwind99** [comment]
Looks like the workaround worked, at le ast for the crashing mods I tested.   If you could check again with latest Food Funk version >= 2.0.3 , it would be appreciated.  Thanks!

**Comment by cofinman** [comment]
Ahoy, dat works! Thank you my Lord. Where i can make donation?

**Comment by Stormwind99** [comment]
Thanks!

Donate link is on this page: https://minecraft.curseforge.com/projects/food-funk
